### PR TITLE
Fix #8: Fix the beast and provide lé schema

### LINKED ISSUE #8: Facebook Messenger Bot

### PR DESCRIPTION
**Pull request by sdulal**

### CODE REVIEW

File: app/bot/example.rb [hunk 1]
```diff
@@ -1,60 +1,20 @@
...
-  #       }
-  #     }
-  #   }
-  # )
+#   sender = message.sender
+
+#   Bot.deliver(
+#     recipient: message.sender,
+#     message: {
+#       text: 'Hello! When and where will you be flying? Please respond in the following form: [Flight Number] (e.g. UAL1183)'
```
Comment (kevinlee12) [inline app/bot/example.rb]: You have a empty slot

**Review by kevinlee12 — APPROVED** [review]
