### PR TITLE
Fix #7: Minor fixes to flight captures

### LINKED ISSUE #7: Flight Data extraction

### PR DESCRIPTION
**Pull request by kevinlee12**

### CODE REVIEW

File: app/bot/flight_data_api.rb [hunk 1]
```diff
@@ -54,6 +55,3 @@ def get_flight_data_from_number(flight_no)
   url = flight_data_url_generator(flight_no)
   return extractor(url)
 end
-
```
Comment (sdulal) [inline app/bot/flight_data_api.rb:57]: 👍

**Review by sdulal — APPROVED** [review]
